---
title: "Publications"
---

#### Journal Articles

-   **Torres-Mendoza, D. M.**, Kheirinejad, S., Ajmal, M., Chembu, A., Palea, D., Whitehead, J., & Lee, D. T. (2024). *Evaluating Exploratory Reading Groups for Supporting Undergraduate Research Pipelines in Computing.* In *Proceedings of the 2024 ACM Conference on International Computing Education Research (ICER '24)* (Vol. 1, pp. 389--405). Association for Computing Machinery. <https://doi.org/10.1145/3632620.3671104>
-   Denner, J., Bell, H., **Torres, D.**, & Green, E. (2024). *Computing education pathways from high school to community college: key strategies for aligning institutional systems.* *Computer Science Education, 34*(1), 68--86. <https://doi.org/10.1080/08993408.2023.2195755>\
-   Denner, J., Potter, S., Anderson, P., & **Torres, D.** (2023). *What predicts the momentum of information and communications technologies students in community college?* *Research in Higher Education, 64*(5), 623--653. <https://doi.org/10.1007/s11162-022-09721-8>\
-   Denner, J., & **Torres, D.** (2023). *How Natural Mentoring is Used by Latinx Youth at a Community Technology Center.* *Journal of Latinos and Education, 22*(1), 339--356. <https://doi.org/10.1080/15348431.2020.1763351>\
-   Lyon, L. A., Schatz, C., Toyama, Y., & **Torres, D.** (2022). *Computer Science Intensive Intervention to Prepare and Engage Underrepresented Novice Students at Community College.* *Community College Journal of Research and Practice, 46*(8), 589--601. <https://doi.org/10.1080/10668926.2021.1894508>\
-   Erenrich, R. K., Braun, R. A., **Torres-Mendoza, D.** M., Stevenson, O. L., Doan, T. H. P., & Klausner, J. D. (2022). *Effectiveness of PrEPTECH: Findings from a 180-Day Randomized Controlled Trial of a Pre-Exposure Prophylaxis Telehealth Intervention.* *JAIDS Journal of Acquired Immune Deficiency Syndromes*. <https://doi.org/10.1097/QAI.0000000000003375>\
-   Werner, L., Denner, J., Campe, S., & **Torres, D.** M. (2020). *Computational sophistication of games programmed by children: a model for its measurement.* *ACM Transactions on Computing Education (TOCE), 20*(2), 1--23. <https://doi.org/10.1145/3379351>\
-   Campe, S., Denner, J., Green, E., & **Torres, D.** (2020). *Pair programming in middle school: variations in interactions and behaviors.* *Computer Science Education, 30*(1), 22--46. <https://doi.org/10.1080/08993408.2019.1648119>\
-   Denner, J., Bean, S., Campe, S., Martinez, J., & **Torres, D.** (2019). *Negotiating trust, power, and culture in a research-practice partnership.* *AERA Open, 5*(2), 1--11. <https://doi.org/10.1177/2332858419858635>

#### Conference Papers

-   Denner, J., Bell, H., **Torres, D.**, & Edwards, J. (2021, May). *Computing Education Pathways from High School to Community College: What Matters to Students?*. In *2021 Conference on Research in Equitable and Sustained Participation in Engineering, Computing, and Technology (RESPECT)* (pp. 1--5). IEEE. <https://doi.org/10.1109/RESPECT51740.2021.9620613>\
-   Osborn, J. C., Dickinson, M., Anderson, B., Summerville, A., Denner, J., **Torres, D.**, ... & Mateas, M. (2019, October). *Is your game generator working? Evaluating Gemini, an intentional generator*. In *Proceedings of the AAAI Conference on Artificial Intelligence and Interactive Digital Entertainment, 15*(1), 59--65. <https://doi.org/10.1609/aiide.v15i1.5225>
